exp_path: ./run/experiment

# =========== Dataset parameters ===========

dataset_folder: ../data
n_max_nodes: 50 # Possible maximum number of nodes in graphs (default: 50)
spectral_emb_dim: 10 # Dimensionality of spectral embeddings for representing graph structures (default: 10)
batch_size: 256 # Batch size for training, controlling the number of samples per gradient update (default: 256)
shuffle_train: True 
shuffle_val: False
shuffle_test: False # Should be always False to fit submission format


# =========== Models ===========
seed: 42 # Seed for random number generators, fixing the randomness in the application (default: 42)

# VAE model parameters
encoder_classname: GIN # Encoder class name for the VAE model (default: GGNN)
decoder_classname: Decoder # Decoder class name for the VAE model (default: Decoder)
hidden_dim_encoder: 64 # Hidden dimension size for encoder layers (default: 64)
hidden_dim_decoder: 256 # Hidden dimension size for decoder layers (default: 256)
latent_dim: 32 # Dimensionality of the latent space in the autoencoder (default: 32)
n_layers_encoder: 2 # Number of layers in the encoder network (default: 2)
n_layers_decoder: 3 # Number of layers in the decoder network (default: 3)

# VAE training parameters
train_autoencoder: True # Whether to train the VAE model
epochs_autoencoder: 200 # Number of training epochs for the autoencoder (default: 200)
vae_lr: 0.001 # Learning rate for the VAE optimizer, typically a small float value (default: 0.001)
vae_scheduler_step_size: 500 # Period of learning rate decay for the VAE optimizer (default: 500)
vae_scheduler_gamma: 0.1 # Multiplicative factor of learning rate decay for the VAE optimizer (default: 0.1)
vae_load_checkpoint_path: null # Path to a checkpoint to load the model from (can restart training from)
vae_save_checkpoint: False

# Diffusion parameters
timesteps: 500 # Number of timesteps for the diffusion (default: 500)
hidden_dim_denoise: 512 # Hidden dimension size for denoising model layers (default: 512)
n_layers_denoise: 3 # Number of layers in the denoising model (default: 3)
n_condition: 7 # Number of distinct condition properties used in conditional vector (default: 7)
dim_condition: 128 # Dimensionality of conditioning vectors for conditional generation (default: 128)

# Diffusion training parameters
train_denoise: True # Whether to train the diffusion model
epochs_denoise: 100 # Number of training epochs for the denoising model (default: 100)
denoise_lr: 0.001 # Learning rate for the denoising model optimizer, typically a small float value (default: 0.001)
denoise_scheduler_step_size: 500 # Period of learning rate decay for the denoising model optimizer (default: 500)
vae_scheduler_gamma: 0.1 # Multiplicative factor of learning rate decay for the denoising model optimizer (default: 0.1)
denoise_load_checkpoint_path: null # Path to a checkpoint to load the model from (can restart training from)
denoise_save_checkpoint: True


# =========== Evaluation ===========
# submission_file_path: null
verbose: True # Whether to print additional information during training and evaluation

save_logs: True # Whether to save logs during training and evaluation
log_level: INFO # Logging level for the application (default: INFO)
